<a href="https://colab.research.google.com/github/Nakulan12/ML/blob/main/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hii")

Hii


In [ ]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
add=0
for i in range (3) :
  value=int(input("Enter the value"))
  print(value)
  add+=value
print("Sum",add)

Enter the value1
1
Enter the value5
5
Enter the value1
1
Sum 7


In [ ]:
a=int(input("Enter the value:"))
b=int(input("Enter the value:"))
c=a+b
if c>0:
  print("Sum",c)
  print("false")
else:
  print("True")

Enter the value:10
Enter the value:20
Sum 30
false


In [ ]:
my_list = [1, "hello", 3.14, True, 5, "world", 7]
print("Initialized list:", my_list)

Initialized list: [1, 'hello', 3.14, True, 5, 'world', 7]


In [ ]:
my_list.append("new_item")
print("List after appending 'new_item':", my_list)

List after appending 'new_item': [1, 'hello', 3.14, True, 5, 'world', 7, 'new_item']


In [ ]:
my_list.insert(2, "inserted_item")
print("inserted_item at index 2:", my_list)

List after inserting 'inserted_item' at index 2: [1, 'hello', 'inserted_item', 3.14, True, 5, 'world', 7, 'new_item']


In [ ]:
my_list.remove("inserted_item")
print(" 'inserted_item':", my_list)

List after removing 'inserted_item': [1, 'hello', 3.14, True, 5, 'world', 7, 'new_item']


In [ ]:
removed_item = my_list.pop(3)
print(f"List after removing item at index 3 ('{removed_item}'):", my_list)

List after removing item at index 3 ('True'): [1, 'hello', 3.14, 5, 'world', 7, 'new_item']


In [ ]:
my_list = [str(item) for item in my_list]
my_list.sort()
print("List after converting to strings and sorting:", my_list)

List after converting to strings and sorting: ['1', '3.14', '5', '7', 'hello', 'new_item', 'world']


In [ ]:
my_list.reverse()
print("List after reversing:", my_list)

List after reversing: ['world', 'new_item', 'hello', '7', '5', '3.14', '1']


In [ ]:
arr=[5,8,10,11,13]
print(arr[1:3])
print(arr[:-2])
print(arr[-3::-1])

[8, 10]
[5, 8, 10]
[10, 8, 5]


# **Numpy**

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(np.mean(a))

[5 7 9]
2.0


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([10,20,30,40,50])
print(arr[1])
print(arr[1:4])

20
[20 30 40]


In [ ]:
import numpy as np
arr = np.array([5,6,7,8])
print(arr)
print(arr[3])
arr[2] = 30
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.size)

[5 6 7 8]
8
[ 5  6 30  8]
int64
(4,)
4


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[1][1])
print(arr2[0][2])
print(arr2.shape)

**2d array**

In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print(arr3.shape)
print(arr3.size)
print(arr3[0][2][1])


3d array

In [ ]:
print(arr[1:3])
print(arr2[0][1:])
print(arr3[0][2][1:])
ones_arr = np.ones((3,2),dtype = "int64")
print(ones_arr)
zeroes_arr = np.zeros((3,2),dtype = "int64")
print(zeroes_arr)
random_arr = np.random.randint(1,100,size = 5)
print(random_arr)

In [ ]:
arr + 2
arr - 3
np.add(arr,10)
arr * 2
print(arr.mean())
print(arr.min())
print(arr.max())
print(arr.var())
print(arr.std())
print(arr.reshape(2,2))

**Pandas**

In [ ]:
import pandas as pd
pd.__version__
df = pd.Series(["apple","orange","cherry"],index=[1,2,3])
df


1     apple
2    orange
3    cherry
dtype: object

In [ ]:
import pandas as pd
df = pd.DataFrame({"winter":{1:"dec",2:"jan"},"dry":{1:"may",2:"june"}},columns=["winter","dry"])
df

winter   dry
1    dec   may
2    jan  june

In [ ]:
from google.colab import files
files.upload()

Saving userdata.csv to userdata.csv


{'userdata.csv': b'S.NO,NAME,AGE,GENDER,CITY\r\n1,RAJ,34,MALE,CHENNAI\r\n2,MANI,NaN,MALE,DELHI\r\n3,KUMAR,55,MALE,NaN\r\n4,RAHUL,23,MALE,MADURAI\r\n5,GOKUL,24,MALE,NaN\r\n6,SHIVA,23,MALE,MUMBAI\r\n7,MALAR,67,FEMALE,NaN\r\n8,BALA,55,MALE,THENI\r\n9,SWATHI,45,FEMALE,TRICHY\r\n10,JOHN,NaN,MALE,CHENNAI\r\n8,BALA,22,MALE,THENI\r\n10,JOHN,25,MALE,CHENNAI\r\n4,RAHUL,23,MALE,MADURAI\r\n'}

In [7]:
import pandas as pd
df=pd.read_csv('userdata.csv')
df

S.NO    NAME   AGE  GENDER     CITY
0      1     RAJ  34.0    MALE  CHENNAI
1      2    MANI   NaN    MALE    DELHI
2      3   KUMAR  55.0    MALE      NaN
3      4   RAHUL  23.0    MALE  MADURAI
4      5   GOKUL  24.0    MALE      NaN
5      6   SHIVA  23.0    MALE   MUMBAI
6      7   MALAR  67.0  FEMALE      NaN
7      8    BALA  55.0    MALE    THENI
8      9  SWATHI  45.0  FEMALE   TRICHY
9     10    JOHN   NaN    MALE  CHENNAI
10     8    BALA  22.0    MALE    THENI
11    10    JOHN  25.0    MALE  CHENNAI
12     4   RAHUL  23.0    MALE  MADURAI

In [8]:
df.isnull().sum()

S.NO      0
NAME      0
AGE       2
GENDER    0
CITY      3
dtype: int64

In [9]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
dtype: bool

In [11]:
df=df.drop_duplicates()

In [12]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [13]:
df.dropna()

S.NO    NAME   AGE  GENDER     CITY
0      1     RAJ  34.0    MALE  CHENNAI
3      4   RAHUL  23.0    MALE  MADURAI
5      6   SHIVA  23.0    MALE   MUMBAI
7      8    BALA  55.0    MALE    THENI
8      9  SWATHI  45.0  FEMALE   TRICHY
10     8    BALA  22.0    MALE    THENI
11    10    JOHN  25.0    MALE  CHENNAI

In [14]:
avg = df['AGE'].mean()
df['AGE'].fillna(avg,inplace=True)
df


/tmp/ipython-input-4002562481.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['AGE'].fillna(avg,inplace=True)


S.NO    NAME   AGE  GENDER     CITY
0      1     RAJ  34.0    MALE  CHENNAI
1      2    MANI  37.3    MALE    DELHI
2      3   KUMAR  55.0    MALE      NaN
3      4   RAHUL  23.0    MALE  MADURAI
4      5   GOKUL  24.0    MALE      NaN
5      6   SHIVA  23.0    MALE   MUMBAI
6      7   MALAR  67.0  FEMALE      NaN
7      8    BALA  55.0    MALE    THENI
8      9  SWATHI  45.0  FEMALE   TRICHY
9     10    JOHN  37.3    MALE  CHENNAI
10     8    BALA  22.0    MALE    THENI
11    10    JOHN  25.0    MALE  CHENNAI

In [15]:
df['CITY'].replace({37.5:'CHENNAI'},inplace=True)
df

/tmp/ipython-input-4269071524.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CITY'].replace({37.5:'CHENNAI'},inplace=True)


S.NO    NAME   AGE  GENDER     CITY
0      1     RAJ  34.0    MALE  CHENNAI
1      2    MANI  37.3    MALE    DELHI
2      3   KUMAR  55.0    MALE      NaN
3      4   RAHUL  23.0    MALE  MADURAI
4      5   GOKUL  24.0    MALE      NaN
5      6   SHIVA  23.0    MALE   MUMBAI
6      7   MALAR  67.0  FEMALE      NaN
7      8    BALA  55.0    MALE    THENI
8      9  SWATHI  45.0  FEMALE   TRICHY
9     10    JOHN  37.3    MALE  CHENNAI
10     8    BALA  22.0    MALE    THENI
11    10    JOHN  25.0    MALE  CHENNAI

In [17]:
df.isnull().sum()

S.NO      0
NAME      0
AGE       0
GENDER    0
CITY      3
dtype: int64